# Generated by Django 4.0.6 on 2022-07-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time registered in created at', verbose_name='Created ad')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time registeres in modified at', verbose_name='Modified at')),
                ('number', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Doble'), ('Triple', 'Triple'), ('Matrimonial', 'Matrimonial')], max_length=20)),
                ('features', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['number', 'type'],
            },
        ),
    ]
