# Generated by Django 4.0.6 on 2022-07-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time registered in created at', verbose_name='Created ad')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time registeres in modified at', verbose_name='Modified at')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_genre', models.CharField(max_length=50)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Detalle Reserva',
                'verbose_name_plural': 'Detalle Reservaciones',
                'ordering': ['reservation', 'room', 'customer_name'],
            },
        ),
    ]
