# Generated by Django 4.0.6 on 2022-07-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='city',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
    ]
